---
title: "entrance-survey"
author: "Nicole Schlosberg"
date: "9/10/2020"
output: html_document
---

opt + cmd + i 
cmd + enter

```{r}
#creating a data frame object (use capital letters and a variable would be lowercase)
DF <- read.csv("hudk4050-entrance-survey.csv", header = TRUE)

#check the variable type
mode(DF$program)
is.numeric(DF$program)

```

#Simple Math 
```{r}
7 + 8
8/2
x <- 8/12
mode(x)

```

#Variable manipulation
```{r}
mean(DF$UTC)
DF$UTC.ms <- DF$UTC*DF$math.stat

```
 
#Vector: *logical*, *integer*, *double*, *character*, complex and raw
```{r}
x <- c(1,2,3)
x
mode(x)

y <- c("a", "b", "c")
y
mode(y)
```

#Factor = list of vectors
```{r}
z <- as.factor(y)
mode(z)
```

#Dataframe
```{r}
Z <- data.frame(z)
Z
```

#Sequences
```{r}
x <- c(1,2,3)

seq(1,10,1)

rep(1,10)

sample(y, 10, replace = TRUE)
```

#Simulate some data
```{r}
s <- seq(1,100,1)

s1 <- sample(s, 1000, replace = TRUE)

p <- seq(0.01,1,0.01)
s2 <- sample(s, 1000, prob = p, replace = TRUE)
```

#Plot
1. Base R - plot (scatterplot default)
2. ggplot2 (standard)
3. Lattice (3D graphs and mapping - interactive work)

```{r}
plot(s1,s2)
plot(s1~s2)
```
#Cross Tabs or Pvot Table
```{r}
t <- table(s2)
t

plot(t)

hist(t)

hist(t, breaks = 10)

hist(t, breaks = c(seq(0,30,2))) #0 to 30 by 2

hist(t, breaks = c(seq(0,30,2)),
  xlab = "Random Sample",
  main = "Our Random Sample", 
  ylim = c(0,10))
  
```
#Two orientations
```{r}
barplot(t)

barplot(t, horiz = TRUE)
```

```{r}
boxplot(s1,s2)

boxplot(s1,s2,
        horizontal = TRUE,
        notch = TRUE,
        col = "blue",
        border = "red")
```

```{r}
hist(DF$compare.shopping)
hist(DF$discussion)

boxplot(DF$compare.shopping~DF$programming,
        ylab = "Do you compare features when shopping?",
        xlab = "Programming Experience")

plot(DF$compare.shopping, DF$discussion)

DF2 <- DF[,5:9] #takes the matrix of only the data that you want with numerical values

pairs(DF2) #has to have the data you want in it so use matrix notation above
```
